# Generated by Django 5.0.6 on 2024-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_itemcolor_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='store.itemcolor'),
        ),
    ]
